
import React from 'react';
import { Calendar, CheckCircle2, Flag, BarChart3, ArrowRight } from 'lucide-react';
import { RoadmapPhase } from '../../types';

interface RoadmapViewProps {
  roadmap: RoadmapPhase[];
}

export const RoadmapView: React.FC<RoadmapViewProps> = ({ roadmap }) => {
  if (!roadmap || roadmap.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center h-96 text-sun-muted border border-dashed border-sun-border rounded-sm bg-sun-right/30">
        <Calendar size={48} className="mb-4 opacity-50" />
        <p>No roadmap generated yet. Complete the wizard to view your plan.</p>
      </div>
    );
  }

  return (
    <div className="space-y-8 animate-fade-in">
      <div className="flex justify-between items-end">
        <div>
          <h2 className="font-serif text-3xl text-sun-primary mb-2">Strategic Roadmap</h2>
          <p className="text-sun-secondary font-sans">
            Your 90-day execution plan generated by the Planner Agent.
          </p>
        </div>
        <div className="text-right hidden md:block">
          <div className="text-xs uppercase tracking-widest text-sun-muted font-bold mb-1">Total Duration</div>
          <div className="font-serif text-xl text-sun-primary">~90 Days</div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {roadmap.map((phase, idx) => {
          const isCurrent = idx === 0; // Assuming Phase 1 is current for new users
          return (
            <div 
              key={idx} 
              className={`
                relative flex flex-col h-full border rounded-sm p-6 transition-all duration-300
                ${isCurrent 
                  ? 'bg-white border-sun-accent shadow-sm ring-1 ring-sun-accent/20' 
                  : 'bg-sun-right/30 border-sun-border hover:bg-white hover:shadow-sm'
                }
              `}
            >
              {/* Phase Header */}
              <div className="flex justify-between items-start mb-6">
                <div>
                  <div className="flex items-center gap-2 mb-2">
                    <span className={`
                      text-[10px] font-bold uppercase tracking-widest px-2 py-1 rounded-full
                      ${isCurrent ? 'bg-sun-accent text-white' : 'bg-sun-border text-sun-secondary'}
                    `}>
                      Phase {idx + 1}
                    </span>
                    <span className="text-xs text-sun-muted font-medium">{phase.duration}</span>
                  </div>
                  <h3 className="font-serif text-xl text-sun-primary">{phase.phaseName}</h3>
                </div>
                {isCurrent && (
                  <div className="w-2 h-2 rounded-full bg-green-500 animate-pulse" title="Active" />
                )}
              </div>

              {/* Objectives */}
              <div className="space-y-6 flex-1">
                
                {/* Deliverables */}
                {phase.deliverables && phase.deliverables.length > 0 && (
                  <div>
                    <h4 className="text-xs font-bold uppercase tracking-widest text-sun-muted mb-3 flex items-center gap-2">
                      <Flag size={12} /> Key Deliverables
                    </h4>
                    <ul className="space-y-2">
                      {phase.deliverables.map((item, i) => (
                        <li key={i} className="text-sm text-sun-secondary flex items-start gap-2">
                          <CheckCircle2 size={14} className="text-sun-tertiary mt-0.5 shrink-0" />
                          <span className="leading-snug">{item}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                {/* Tasks (Condensed) */}
                <div>
                  <h4 className="text-xs font-bold uppercase tracking-widest text-sun-muted mb-3 flex items-center gap-2">
                    <ArrowRight size={12} /> Execution Steps
                  </h4>
                  <ul className="space-y-2">
                    {phase.items.slice(0, 4).map((item, i) => (
                      <li key={i} className="text-xs text-sun-secondary bg-white border border-sun-border/50 p-2 rounded-sm">
                        {item}
                      </li>
                    ))}
                    {phase.items.length > 4 && (
                      <li className="text-[10px] text-sun-tertiary italic pl-1">
                        + {phase.items.length - 4} more tasks
                      </li>
                    )}
                  </ul>
                </div>

              </div>

              {/* Footer / KPIs */}
              {phase.kpis && phase.kpis.length > 0 && (
                <div className="mt-8 pt-4 border-t border-sun-border/50">
                  <h4 className="text-[10px] font-bold uppercase tracking-widest text-sun-muted mb-2 flex items-center gap-2">
                    <BarChart3 size={10} /> Success Metrics
                  </h4>
                  <div className="flex flex-wrap gap-2">
                    {phase.kpis.map((kpi, i) => (
                      <span key={i} className="text-[10px] font-medium bg-sun-bg px-2 py-1 rounded text-sun-secondary border border-sun-border">
                        {kpi}
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
};
